### ISSUE TITLE
崩溃！各种崩溃！

### ISSUE THREAD

**Issue by JimsC** [danielvictor/helpshift-android-sdk-examples#13]
运营商需要helpshift，我是技术人员，负责接入，我们的游戏的sdk要尽量低，要覆盖尽可能多的用户，所以不能用你们最新的sdk，我下了一些旧的sdk，用的是3.11，接入到游戏后，4个界面，help，contact us，faq，question，只有contact us界面能够拉起来，其他界面全部崩溃，全部！
从报错来看，是你们sdk内部错误，贴出报错代码
03-03 14:12:42.193: E/AndroidRuntime(5683): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myhsdemon/com.helpshift.HSQuestion}: android.view.InflateException: Binary XML file line #29: Error inflating class android.view.View
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2664)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.app.ActivityThread.access$900(ActivityThread.java:187)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.os.Handler.dispatchMessage(Handler.java:111)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.os.Looper.loop(Looper.java:194)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.app.ActivityThread.main(ActivityThread.java:5869)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at java.lang.reflect.Method.invoke(Native Method)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at java.lang.reflect.Method.invoke(Method.java:372)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)
03-03 14:12:42.193: E/AndroidRuntime(5683): Caused by: android.view.InflateException: Binary XML file line #29: Error inflating class android.view.View
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.view.LayoutInflater.createView(LayoutInflater.java:639)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:671)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:65)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:688)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:812)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:815)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:815)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:510)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:420)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at com.helpshift.HSQuestionFragment.onCreateView(HSQuestionFragment.java:399)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1504)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:915)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1099)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1201)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:292)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:812)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:510)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:420)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:371)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:437)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.app.Activity.setContentView(Activity.java:2205)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at com.helpshift.HSQuestion.onCreate(HSQuestion.java:65)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.app.Activity.performCreate(Activity.java:6127)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2617)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	... 10 more
03-03 14:12:42.193: E/AndroidRuntime(5683): Caused by: java.lang.reflect.InvocationTargetException
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at java.lang.reflect.Constructor.newInstance(Native Method)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.view.LayoutInflater.createView(LayoutInflater.java:613)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	... 36 more
03-03 14:12:42.193: E/AndroidRuntime(5683): Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 13
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.content.res.TypedArray.getDrawable(TypedArray.java:747)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.view.View.<init>(View.java:3847)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.view.View.<init>(View.java:3755)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	at android.view.View.<init>(View.java:3734)
03-03 14:12:42.193: E/AndroidRuntime(5683): 	... 39 more

我接了那么多sdk，从来没有哪一家sdk像你们这样，内部报这么多错误，还直接崩溃，真不知道我们的运营商为什么选择了你们，是市场上只有你们一家了吗？如果是这样，希望你们早点倒闭！

**Comment by ljaf007** [comment]
哈哈哈，哥们，我也要接入，别吓我
