### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by BugsBunnyBR** [danielvictor/helpshift-android-sdk-examples#6]
Hi,I am getting this error while using the sdk version 3.4.2 with gradle.
```Java
 Reseting review counter
D/HelpShiftDebug(28295): org.json.JSONException: No value for pr
D/HelpShiftDebug(28295):        at org.json.JSONObject.get(JSONObject.java:355)
D/HelpShiftDebug(28295):        at org.json.JSONObject.getJSONObject(JSONObject.java:574)
D/HelpShiftDebug(28295):        at com.helpshift.HSApiData.resetReviewCounter(HSApiData.java:784)
D/HelpShiftDebug(28295):        at com.helpshift.Helpshift.install(Helpshift.java:238)
D/HelpShiftDebug(28295):        at com.helpshift.Helpshift.install(Helpshift.java:163)

```

Any idea?

**Comment by danielvictor** [comment]
These are expected debug logs. You can safely ignore them.
